---

routers:
  hosts:
    R1: 
      ansible_host: 192.168.100.11
    R2: 
      ansible_host: 192.168.100.12
    R3: 
      ansible_host: 192.168.100.13
    R4: 
      ansible_host: 192.168.100.14
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: vyos
    ansible_network_os: vyos.vyos.vyos
    ansible_connection: network_cli
    
